feat: PyNet model implemented
soumik12345/pynet pull request #1
Opened 2023-06-22 19:03 UTC by sanatsingh

Changes :
- [ ] Python version change in pyproject.toml
- [ ] Added all level based modules
- [ ] Added PyNet model
- [ ] Added test cases
- [ ] Fixed activation from relu to leaky relu in UpSampleConvLayer in layers
- [ ] Fixed double padding issue in ConvLayer and UpSampleConvLayer in layers
- [ ] Fixed a instantiation issue (>= instead of >) in multi_conv_block

Please review and approve merge

2023-06-23 19:17 UTC, soumik12345 requested changes
Hi @sanatsingh, Great job on the PR!!!
I have shared some feedback, please address them.

2023-06-23 19:17 UTC, soumik12345 commented on pynet/model/pynet.py
> +def PyNet(apply_norm=True, apply_norm_l1=False, use_sigmoid=True):
- Please add type assertions.
- Let's add a flag here called `return_lower_level_outputs: bool = False`.

2023-06-23 19:17 UTC, soumik12345 commented on pynet/model/pynet.py
> +    return keras.Model(inputs=input_tensor, outputs=[l0_out_final,l1_out_final,l2_out_final,l3_out_final,l4_out_final,l5_out_final], name='PyNet')
Also, let's make it so that
```python
if return_lower_level_outputs:
    outputs=[l0_out_final, l1_out_final, l2_out_final, l3_out_final, l4_out_final, l5_out_final]
else:
    outputs=l0_out_final
```

2023-06-23 19:21 UTC, soumik12345 commented on pynet/model/pynet.py
@sanatsingh 

Let's also try to make the implementation align with the [`Task`](https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/task.py#L25) API from KerasCV. This would enable us to take advantage of advance features such as presets.

You can refer to this PR for reference: https://github.com/keras-team/keras-cv/pull/1831

2023-06-25 15:46 UTC, sanatsingh commented on pynet/tests/model/test_pynet.py
> +        self.assertEqual(l5_pass_b.shape,(1,28,28,256))
Calculated manually and verified from PyTorch implementation

2023-06-25 15:47 UTC, sanatsingh commented on pynet/tests/model/test_pynet.py
> +        self.assertEqual(l4_pass_b.shape,(1,56,56,128))
Calculated manually and verified from PyTorch implementation

2023-06-25 15:47 UTC, sanatsingh commented on pynet/tests/model/test_pynet.py
> +
Calculated manually and verified from PyTorch implementation

2023-06-25 15:48 UTC, sanatsingh commented on .gitignore
> +test.ipynb
Done

2023-06-25 15:49 UTC, sanatsingh commented on pynet/tests/model/test_pynet.py
> +        self.assertEqual(l3_pass_b.shape,(1,112,112,64))
Calculated manually and verified from PyTorch implementation

2023-06-25 15:54 UTC, sanatsingh commented on pyproject.toml
> +python = "^3.9"
I am on python 3.9 with tf 2.10, My PopOS dual boot is broken so working from windows
(Why tf 2.10 -- click [here](https://www.tensorflow.org/install/source_windows#:~:text=on%20a%20GPU.-,Note%3A%20GPU%20support%20on%20native%2DWindows%20is%20only%20available%20for%202.10%20or%20earlier%20versions%2C%20starting%20in%20TF%202.11%2C%20CUDA%20build%20is%20not%20supported%20for%20Windows.%20For%20using%20TensorFlow%20GPU%20on%20Windows,-%2C%20you%20will%20need))

2023-06-25 15:54 UTC, sanatsingh commented on pynet/model/modules.py
> +def level_4(l4_out_1, l5_pass_a, l5_pass_b, apply_norm, use_sigmoid):
Done

2023-06-25 15:54 UTC, sanatsingh commented on pynet/model/modules.py
> +def level_2(l2_out_1, l3_pass_a, l3_pass_b, apply_norm, use_sigmoid):
Done

2023-06-25 15:55 UTC, sanatsingh commented on pynet/model/modules.py
> +def level_1(l1_out_1, l2_pass_a, l2_pass_b, apply_norm, use_sigmoid):
Done

2023-06-25 15:55 UTC, sanatsingh commented on pynet/model/modules.py
> +def level_3(l3_out_1, l4_pass_a, l4_pass_b, apply_norm, use_sigmoid):
Done

2023-06-25 15:55 UTC, sanatsingh commented on pynet/model/modules.py
> +    l5_out_4 = MultiConvolutionBlock(512, 3, apply_norm)(l5_out_3)
Done

2023-06-25 15:55 UTC, sanatsingh commented on pynet/model/modules.py
> +    l4_out_5 = MultiConvolutionBlock(256, 3, apply_norm)(l4_out_4)
Done

2023-06-25 15:55 UTC, sanatsingh commented on pynet/model/modules.py
> +    l5_pass_b = UpSampleConvLayer(256, 3)(l5_out_4)
Done

2023-06-25 15:55 UTC, sanatsingh commented on pynet/model/modules.py
> +    l4_out_6 = MultiConvolutionBlock(256, 3, apply_norm)(l4_cat_2)
Done

2023-06-25 15:55 UTC, sanatsingh commented on pynet/model/modules.py
> +    l4_pass_b = UpSampleConvLayer(128, 3)(l4_out_6)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/modules.py
> +    l3_out_5 = MultiConvolutionBlock(128, 5, apply_norm)(l3_out_4)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/modules.py
> +    l3_out_6 = MultiConvolutionBlock(128, 3, apply_norm)(l3_cat_2)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/modules.py
> +    l3_pass_b = UpSampleConvLayer(64, 3)(l3_out_6)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/modules.py
> +    l2_out_2 = MultiConvolutionBlock(64, 5, apply_norm)(l2_cat_1)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/modules.py
> +    l2_out_6 = MultiConvolutionBlock(64, 7, apply_norm)(l2_out_5)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/modules.py
> +    l2_out_7 = MultiConvolutionBlock(64, 5, apply_norm)(l2_cat_3)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/modules.py
> +    l2_out_8 = MultiConvolutionBlock(64, 3, apply_norm)(l2_cat_4)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/modules.py
> +    l2_pass_b = UpSampleConvLayer(32, 3)(l2_out_8)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/modules.py
> +    l1_out_2 = MultiConvolutionBlock(32, 5, apply_norm)(l1_cat_1)
Done

2023-06-25 15:56 UTC, sanatsingh commented on pynet/model/pynet.py
> +    l4_out_1 = MultiConvolutionBlock(256, 3, apply_norm)(l3_pool)
Done

2023-06-25 15:57 UTC, sanatsingh commented on pynet/model/pynet.py
> +    l0_out_final = level_0(l1_pass, use_sigmoid) # 448x448
Done

2023-06-25 15:57 UTC, sanatsingh commented on pynet/model/pynet.py
> +    return keras.Model(inputs=input_tensor, outputs=[l0_out_final,l1_out_final,l2_out_final,l3_out_final,l4_out_final,l5_out_final], name='PyNet')
Done

2023-06-25 15:57 UTC, sanatsingh commented on pynet/model/modules.py
> +    l1_out_8 = MultiConvolutionBlock(32, 7, apply_norm)(l1_out_7)
Done

2023-06-25 15:57 UTC, sanatsingh commented on pynet/model/modules.py
> +    l1_out_9 = MultiConvolutionBlock(32, 5, apply_norm)(l1_cat_3)
Done

2023-06-25 15:57 UTC, sanatsingh commented on pynet/model/modules.py
> +    l1_out_10 = MultiConvolutionBlock(32, 3, apply_norm)(l1_cat_4)
Done

2023-06-25 15:57 UTC, sanatsingh commented on pynet/model/modules.py
> +    l1_pass = UpSampleConvLayer(16, 3)(l1_out_10)
Done

2023-06-25 15:57 UTC, sanatsingh commented on pynet/model/modules.py
> +    l1 = MultiConvolutionBlock(32, 3, True)(inp)
Done

2023-06-25 15:57 UTC, sanatsingh commented on pynet/model/modules.py
> +    l2 = MultiConvolutionBlock(64, 3, True)(l2)
Done

2023-06-25 15:58 UTC, sanatsingh commented on pynet/model/modules.py
> +    l3 = MultiConvolutionBlock(128, 3, True)(l3)
Done

2023-06-25 15:58 UTC, sanatsingh commented on pynet/model/modules.py
> +    l4 = MultiConvolutionBlock(512, 3, True)(l4)
Done

2023-06-25 15:58 UTC, sanatsingh commented on pynet/model/pynet.py
> +    l1_out_1 = MultiConvolutionBlock(32, 3, apply_norm_l1)(input_tensor)
Done

2023-06-25 15:58 UTC, sanatsingh commented on pynet/model/pynet.py
> +    l2_out_1 = MultiConvolutionBlock(64, 3, apply_norm)(l1_pool)
Done

2023-06-25 15:58 UTC, sanatsingh commented on pynet/model/pynet.py
> +    l3_out_1 = MultiConvolutionBlock(128, 3, apply_norm)(l2_pool)
Done

2023-06-25 15:58 UTC, sanatsingh commented on pynet/model/pynet.py
> +def PyNet(apply_norm=True, apply_norm_l1=False, use_sigmoid=True):
Done

2023-06-25 15:58 UTC, sanatsingh commented on pynet/model/pynet.py
> +    return keras.Model(inputs=input_tensor, outputs=[l0_out_final,l1_out_final,l2_out_final,l3_out_final,l4_out_final,l5_out_final], name='PyNet')
Done

2023-06-27 18:01 UTC, soumik12345 requested changes
Hi @sanatsingh 
Great job acting upon the feedback.
One more minor change and we can merge.

2023-06-27 18:01 UTC, soumik12345 commented on pynet/model/pynet.py
> +    return keras.Model(inputs=input_tensor, outputs=outputs, name="PyNet")
Nice!

2023-06-28 18:08 UTC, soumik12345 commented
Hi @sanatsingh 
We can merge this PR once you make this small change 🙂

2023-06-28 20:33 UTC, sanatsingh commented
Done

2023-07-01 05:18 UTC, soumik12345 approved these changes

2023-07-01 05:18 UTC, merged