Port to Keras Core complete
soumik12345/pynet pull request #11
Opened 2023-08-04 07:24 UTC by sanatsingh

Made necessary changes for porting to keras_core (TF backend)

2023-08-05 07:50 UTC, soumik12345 requested changes
Hi @sanatsingh 
Great job on the PR!
Left some feedback...

2023-08-05 07:50 UTC, soumik12345 commented on .devcontainer/setup.sh
> +sudo pip install -q keras-core
Little curious as to why `sudo` is required!

```suggestion
sudo pip install namex
sudo apt install python3.10-venv
sudo git clone https://github.com/keras-team/keras-core.git && cd keras-core && python pip_build.py --install
```

2023-08-05 07:50 UTC, soumik12345 commented on pynet/model/modules.py
> +    l4_cat_1 = keras.layers.Concatenate(axis=-1)([l4_out_1, l5_pass_a])
Nice!

2023-08-05 07:50 UTC, soumik12345 commented on pynet/model/layers.py
>  import tensorflow_addons as tfa
Let's get rid of `tensorflow_addons` as well! We're currently using it for InstanceNorm, which can be replaced with [`keras.layers.GroupNormalization(groups=<number-of-channels-of-input-tensor>)`](https://keras.io/keras_core/api/layers/normalization_layers/group_normalization/).

2023-08-08 16:13 UTC, sanatsingh commented on .devcontainer/setup.sh
> +sudo pip install -q keras-core
Not sure about sudo but do we want to install keras-core directly from git repo or stick to stable releases based on versions?

2023-08-08 16:14 UTC, sanatsingh commented on pynet/model/layers.py
>  import tensorflow_addons as tfa
Done

2023-08-08 17:05 UTC, sanatsingh commented on .devcontainer/setup.sh
> +sudo pip install -q keras-core
Updated installation command

2023-08-16 07:31 UTC, soumik12345 approved these changes

2023-08-16 07:32 UTC, merged