Feat/train test step
soumik12345/pynet pull request #9
Opened 2023-07-11 18:42 UTC by sanatsingh

Implementing train and test steps

- [x] Added train loss computation
- [ ] Added eval loss computation
- [ ] Defined train and test steps

2023-07-14 08:16 UTC, soumik12345 requested changes
@sanatsingh 
Mighty work. on the PR!
Requested a few changes.

2023-07-14 08:16 UTC, soumik12345 commented on pynet/model/pynet.py
> +        ssim_loss: keras.losses.Loss,
Nitpick: since we already know the losses being used, it's better if we define the losses directly inside `compile()` instead of passing them.

2023-07-14 08:16 UTC, soumik12345 commented on pynet/model/pynet.py
> +        l0_loss_psnr = 20 * math.log10(1.0 / math.sqrt(l0_mse_loss))
Use [`tf.image.psnr`](https://www.tensorflow.org/api_docs/python/tf/image/psnr)

2023-07-14 08:16 UTC, soumik12345 commented on pynet/model/pynet.py
> +        }
It should be a dictionary mapper string to metric, not list of metrics.

2023-07-14 08:16 UTC, soumik12345 commented
Fixes https://github.com/soumik12345/pynet/issues/6

2023-07-18 15:21 UTC, sanatsingh commented on pynet/model/pynet.py
> +        l0_loss_psnr = 20 * math.log10(1.0 / math.sqrt(l0_mse_loss))
We are already calculating MSE so reusing it for psnr calculation, although tf.image.psnr would look cleaner. LMK what you think

2023-07-19 13:48 UTC, soumik12345 commented on pynet/model/pynet.py
> +        l0_loss_psnr = 20 * math.log10(1.0 / math.sqrt(l0_mse_loss))
Using [`tf.image.psnr`](https://www.tensorflow.org/api_docs/python/tf/image/psnr) will make it more readable.

2023-07-19 13:51 UTC, soumik12345 commented on pynet/model/pynet.py
> +        ssim_loss: keras.losses.Loss,
@sanatsingh I meant that we should "define" the losses inside `compile` instead of passing them as arguments, like [this](https://github.com/keras-team/keras-core/blob/main/examples/keras_io/tensorflow/vision/zero_dce.py#L316).

2023-07-19 13:58 UTC, soumik12345 requested changes
Hi @sanatsingh 
I have left one feedback.
Let's also resolve our unresolved conversations from the previous round of feedback (this will also mend the CI).

2023-07-19 13:58 UTC, soumik12345 commented on pynet/model/pynet.py
> +        }
I had some [conversation](https://github.com/keras-team/keras-core/issues/485) with [François](https://github.com/fchollet) recently, even though this would ensure that the values would turn up in the progress bar, it won't be available in the callback (so, no experiment tracking 🥲) or on `history.history`. So, the best way to solve this issue is to create `Mean` trackers for the different metrics to track and call `update_state()` on them in `train_step`. You can refer to [this example](https://github.com/keras-team/keras-core/blob/main/examples/keras_io/tensorflow/vision/zero_dce.py#L316).

2023-07-20 13:16 UTC, sanatsingh commented on pynet/model/pynet.py
> +        l0_loss_psnr = 20 * math.log10(1.0 / math.sqrt(l0_mse_loss))
Done

2023-07-20 14:54 UTC, sanatsingh commented on pynet/model/pynet.py
> +        ssim_loss: keras.losses.Loss,
Ok, I defined them as default values so as to allow change in loss functions

2023-07-20 14:55 UTC, sanatsingh commented on pynet/model/pynet.py
> +        ssim_loss: keras.losses.Loss,
Done

2023-07-20 15:01 UTC, sanatsingh reviewed
Changes made

2023-07-20 15:01 UTC, sanatsingh commented on pynet/model/pynet.py
> +        }
Done

2023-07-23 17:23 UTC, soumik12345 approved these changes
Thanks for the PR!

2023-07-23 17:23 UTC, merged